platform :ios, '8.0'

use_frameworks!

target 'DLDebugExtension_Example' do
  pod 'DLDebugExtension', :configuration => 'Debug', :path => '../'
  pod 'CocoaDebug', :configuration => 'Debug', :path => '../../CocoaDebug'
  pod 'FLEX', '~> 3.0', :configuration => 'Debug'

  target 'DLDebugExtension_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
