use_frameworks!

target 'DLDebugExtension_Example' do
  pod 'DLDebugExtension', :path => '../'

  target 'DLDebugExtension_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
